### PR TITLE
Enable Kotlin build and clean up versioning

### PR DESCRIPTION
**Pull request by muandrew**
* also add example gradle.property file

### CODE REVIEW

**Comment by muandrew** [comment]
note: that I also wrote a simple example bot of each with random movement. I don't know if anyone would be interested in having that in the repo as RobotController.kt.txt or RobotController.scala.txt. I also need help adding classes to the allowed list of classes, but am not sure what classes the team actually wants to allow. ¯\_(ツ)_/¯

**Comment by bovard** [comment]
@muandrew can list a gist to that? need to make sure the compile/match server supports it

**Comment by muandrew** [comment]
https://gist.github.com/muandrew/dcb6fe1899f6f95a4144b67876c134e3
You need to update the allowed classes.
There is also a corresponding pull request for battlecode-client-17
https://github.com/battlecode/battlecode-client-17/pull/116

**Comment by kazimuth** [comment]
@muandrew 
Thanks! I'll review this soon.

**Comment by muandrew** [comment]
bump

**Pull request merged**
